# -*- coding: utf-8 -*-
"""phishing_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFUhcRGT8R7cRh1vz_SNDf9ji7hkQuTi
"""

# AIAP-22 batch

import pandas as pd

# Load the dataset into a pandas DataFrame, specifying the absolute path
df = pd.read_csv('data/phishing_data.csv')

# Display the first 5 rows of the DataFrame
df.head()

"""## Initial Data Inspection

### Subtask:
Check the dataset's basic information such as column names, data types, and non-null values using `df.info()` and descriptive statistics using `df.describe()`.

**Reasoning**:
To fulfill the subtask, I will display the DataFrame's information using `df.info()` to check column names, data types, and non-null values, and then generate descriptive statistics using `df.describe()` for numerical columns.
"""

print("DataFrame Info:")
df.info()

print("\nDescriptive Statistics:")
df.describe()

"""## Check for Missing Values

### Subtask:
Identify if there are any missing values in the dataset and quantify them per column.

**Reasoning**:
To identify and quantify missing values per column, I will calculate the sum of null values for each column in the DataFrame `df` and display the results.
"""

print("Missing values per column:")
df.isnull().sum()

"""## Target Variable Analysis

### Subtask:
Analyze the distribution of the target variable ('label') to understand class balance.

**Reasoning**:
To analyze the distribution of the target variable 'label', I will use the `.value_counts()` method to get the counts of each unique value and then calculate their respective percentages.
"""

print("Distribution of 'label' column (counts):")
label_counts = df['label'].value_counts()
print(label_counts)

print("\nDistribution of 'label' column (percentages):")
label_percentages = df['label'].value_counts(normalize=True) * 100
print(label_percentages)

"""## Exploratory Data Analysis (EDA)

### Subtask:
Perform initial data cleaning by dropping unnecessary columns and correcting illogical values, then visualize the relationship between categorical features and the target variable.

**Reasoning**:
To begin the data cleaning, I will drop the 'Unnamed: 0' column which appears to be an artifact, and then correct the illogical negative values in the 'NoOfImage' column by replacing them with zero, as the count of images cannot be negative.
"""

print("Original shape of DataFrame:", df.shape)

# Drop the 'Unnamed: 0' column
df = df.drop('Unnamed: 0', axis=1)
print("Shape after dropping 'Unnamed: 0':", df.shape)

# Correct illogical values in 'NoOfImage' by replacing negative values with 0
initial_negative_images = (df['NoOfImage'] < 0).sum()
if initial_negative_images > 0:
    df['NoOfImage'] = df['NoOfImage'].apply(lambda x: max(0, x))
    print(f"Corrected {initial_negative_images} negative values in 'NoOfImage' to 0.")
else:
    print("No negative values found in 'NoOfImage' to correct.")

print("First 5 rows after cleaning steps:")
print((df.head()))

"""**Reasoning**:
To visualize the relationship between categorical features and the target variable, I will create count plots using `seaborn` for 'Industry' and 'HostingProvider' against the 'label' column. This will show the distribution of phishing (label=1) vs. legitimate (label=0) websites within each category.


"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set up the plot style
sns.set_style("whitegrid")

# Create subplots for Industry vs. Label and HostingProvider vs. Label
fig, axes = plt.subplots(1, 2, figsize=(20, 8))

# Plot for 'Industry' vs. 'label'
sns.countplot(data=df, x='Industry', hue='label', ax=axes[0], palette='viridis')
axes[0].set_title('Distribution of Label by Industry')
axes[0].set_xlabel('Industry')
axes[0].set_ylabel('Count')
axes[0].tick_params(axis='x', rotation=45)
axes[0].legend(title='Label', labels=['Legitimate', 'Phishing'])

# Plot for 'HostingProvider' vs. 'label'
sns.countplot(data=df, x='HostingProvider', hue='label', ax=axes[1], palette='plasma')
axes[1].set_title('Distribution of Label by Hosting Provider')
axes[1].set_xlabel('Hosting Provider')
axes[1].set_ylabel('Count')
axes[1].tick_params(axis='x', rotation=45)
axes[1].legend(title='Label', labels=['Legitimate', 'Phishing'])

plt.tight_layout()
plt.show()

"""## Exploratory Data Analysis (EDA)

### Subtask:
Perform imputation for the missing values in `LineOfCode` using the median. Afterwards, visualize the distributions of key numerical features such as `LineOfCode`, `LargestLineLength`, `NoOfURLRedirect`, and `DomainAgeMonths` using histograms, differentiated by the target variable (`label`), to gain initial insights into their patterns.

**Reasoning**:
To perform imputation for the missing values in `LineOfCode` using its median and then visualize the distributions of specified numerical features differentiated by the target variable, I will first calculate the median and fill the missing values, then create histograms for each feature using subplots.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 1. Calculate the median of the 'LineOfCode' column
median_line_of_code = df['LineOfCode'].median()
print(f"Median of LineOfCode: {median_line_of_code}")

# 2. Fill the missing values (NaNs) in the 'LineOfCode' column with the calculated median
df['LineOfCode'].fillna(median_line_of_code, inplace=True)
print("Missing values in 'LineOfCode' filled with median.")

# 3. Verify that there are no more missing values in 'LineOfCode'
print("Missing values in 'LineOfCode' after imputation:")
print(df['LineOfCode'].isnull().sum())

# 4. Select a few important numerical features for initial visualization
numerical_features = ['LineOfCode', 'LargestLineLength', 'NoOfURLRedirect', 'DomainAgeMonths']

# Set up the plot style
sns.set_style("whitegrid")

# Create subplots for the distributions
fig, axes = plt.subplots(len(numerical_features), 1, figsize=(12, 5 * len(numerical_features)))

# 5. For each selected numerical feature, create a histogram differentiated by 'label'
for i, feature in enumerate(numerical_features):
    sns.histplot(data=df, x=feature, hue='label', kde=True, ax=axes[i], palette='coolwarm')
    axes[i].set_title(f'Distribution of {feature} by Label')
    axes[i].set_xlabel(feature)
    axes[i].set_ylabel('Frequency')
    # 6. Add legend for clarity
    axes[i].legend(title='Label', labels=['Phishing (1)', 'Legitimate (0)'], loc='upper right')

# 7. Use plt.tight_layout() and plt.show() to display the plots
plt.tight_layout()
plt.show()

"""**Reasoning**:
To address the `FutureWarning` regarding `inplace=True` in pandas, I will modify the `fillna` operation to directly assign the result back to the DataFrame column, ensuring correct behavior in future pandas versions.


"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 1. Calculate the median of the 'LineOfCode' column
median_line_of_code = df['LineOfCode'].median()
print(f"Median of LineOfCode: {median_line_of_code}")

# 2. Fill the missing values (NaNs) in the 'LineOfCode' column with the calculated median
df['LineOfCode'] = df['LineOfCode'].fillna(median_line_of_code)
print("Missing values in 'LineOfCode' filled with median.")

# 3. Verify that there are no more missing values in 'LineOfCode'
print("Missing values in 'LineOfCode' after imputation:")
print(df['LineOfCode'].isnull().sum())

# 4. Select a few important numerical features for initial visualization
numerical_features = ['LineOfCode', 'LargestLineLength', 'NoOfURLRedirect', 'DomainAgeMonths']

# Set up the plot style
sns.set_style("whitegrid")

# Create subplots for the distributions
fig, axes = plt.subplots(len(numerical_features), 1, figsize=(12, 5 * len(numerical_features)))

# 5. For each selected numerical feature, create a histogram differentiated by 'label'
for i, feature in enumerate(numerical_features):
    sns.histplot(data=df, x=feature, hue='label', kde=True, ax=axes[i], palette='coolwarm')
    axes[i].set_title(f'Distribution of {feature} by Label')
    axes[i].set_xlabel(feature)
    axes[i].set_ylabel('Frequency')
    # 6. Add legend for clarity
    axes[i].legend(title='Label', labels=['Phishing (1)', 'Legitimate (0)'], loc='upper right')

# 7. Use plt.tight_layout() and plt.show() to display the plots
plt.tight_layout()
plt.show()

"""## Exploratory Data Analysis (EDA)

### Subtask:
Visualize correlations between numerical features using a heatmap and display the distributions of key numerical features against the target variable using box plots.

**Reasoning**:
To visualize the correlations between numerical features, I will compute the correlation matrix of the DataFrame's numerical columns and then create a heatmap using `seaborn.heatmap`. This will help identify highly correlated features.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Select only numerical columns for correlation calculation
numerical_df = df.select_dtypes(include=['number'])

# Calculate the correlation matrix
correlation_matrix = numerical_df.corr()

# Set up the matplotlib figure
plt.figure(figsize=(14, 10))

# Create a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""**Reasoning**:
To display the distributions of key numerical features against the target variable using box plots, I will iterate through selected numerical features and create a box plot for each, showing their spread and central tendency for both 'Legitimate' and 'Phishing' labels. This will allow for easy comparison of feature values between the two classes.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Select numerical features for box plots (same as used for histograms, or pick a few key ones)
numerical_features_for_boxplots = ['LineOfCode', 'LargestLineLength', 'NoOfURLRedirect', 'DomainAgeMonths', 'NoOfImage', 'NoOfSelfRef', 'NoOfExternalRef']

# Set up the plot style
sns.set_style("whitegrid")

# Create subplots for the box plots
fig, axes = plt.subplots(len(numerical_features_for_boxplots), 1, figsize=(12, 6 * len(numerical_features_for_boxplots)))

# For each selected numerical feature, create a box plot differentiated by 'label'
for i, feature in enumerate(numerical_features_for_boxplots):
    sns.boxplot(data=df, x='label', y=feature, ax=axes[i], palette='viridis')
    axes[i].set_title(f'Box Plot of {feature} by Label')
    axes[i].set_xlabel('Label (0: Legitimate, 1: Phishing)')
    axes[i].set_ylabel(feature)

plt.tight_layout()
plt.show()

"""## Final Task

### Subtask:
Summarize the key insights from the initial data inspection and EDA, and propose next steps for data preprocessing or model building.

## Summary:

### Data Analysis Key Findings

*   The dataset `phishing_data.csv` was successfully loaded, containing 10,500 entries and 16 columns.
*   The `LineOfCode` column had 2,355 missing values, which were later imputed using the median value of 620.0. All other columns were complete.
*   The `NoOfImage` column contained illogical negative values (377 instances), which were corrected by setting them to 0.
*   The `Unnamed: 0` column was identified as an unnecessary identifier and was dropped, reducing the DataFrame to 15 columns.
*   The target variable, `label`, shows a relatively balanced distribution: 55.038% (5,779 instances) are classified as '1' (phishing), and 44.962% (4,721 instances) are classified as '0' (legitimate).
*   Categorical features (`Industry` and `HostingProvider`) and numerical features (`LineOfCode`, `LargestLineLength`, `NoOfURLRedirect`, `DomainAgeMonths`) show distinct distributions when differentiated by the `label`, suggesting their potential predictive power.

### Insights or Next Steps

*   **Categorical Feature Encoding:** The `Industry` and `HostingProvider` columns, currently of object type, need to be converted into a numerical format (e.g., using one-hot encoding or label encoding) before being used in machine learning models.
*   **Feature Scaling/Transformation:** Given the wide ranges observed in some numerical features (e.g., `LineOfCode`, `LargestLineLength`), applying feature scaling (e.g., standardization or normalization) might be beneficial for algorithms sensitive to feature magnitudes. Further investigation into outliers might also be warranted.
*   **Model Building:** With the data cleaned and initial insights gained, the next step involves preparing the data for model training, including splitting into training and testing sets, and then proceeding with model selection and evaluation.

# Task
The current plan is to preprocess features by one-hot encoding categorical features ('Industry', 'HostingProvider') and scaling numerical features. Then, split the processed data into training and testing sets, train a Random Forest Classifier, evaluate its performance using relevant metrics, and finally, summarize the model's performance and discuss future steps for improvement.

## Feature Preprocessing

### Subtask:
One-hot encode categorical features ('Industry', 'HostingProvider') and scale numerical features.

**Reasoning**:
To begin feature preprocessing, I will separate the dataset into features (X) and the target variable (y). Then, I will identify the categorical columns ('Industry', 'HostingProvider') and apply one-hot encoding to them using `pd.get_dummies` with `drop_first=True` to prevent multicollinearity.
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler

# 1. Separate features (X) from the target variable (y)
X = df.drop('label', axis=1)
y = df['label']

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

# 2. Identify the categorical features
categorical_features = ['Industry', 'HostingProvider']

# 3. Apply one-hot encoding to these categorical features
X_categorical = pd.get_dummies(X[categorical_features], drop_first=True)

print("Shape of one-hot encoded categorical features:", X_categorical.shape)
print("First 5 rows of one-hot encoded categorical features:")
print(X_categorical.head())

"""**Reasoning**:
Now that the categorical features are one-hot encoded, I will identify the numerical features, apply StandardScaler to them, convert the scaled array back to a DataFrame with original column names, and finally concatenate the scaled numerical features with the one-hot encoded categorical features to form the complete preprocessed feature set `X_processed`.


"""

import pandas as pd
from sklearn.preprocessing import StandardScaler

# 1. Separate features (X) from the target variable (y)
X = df.drop('label', axis=1)
y = df['label']

# 2. Identify the categorical features
categorical_features = ['Industry', 'HostingProvider']

# 3. Apply one-hot encoding to these categorical features
X_categorical = pd.get_dummies(X[categorical_features], drop_first=True)

# 4. Identify numerical features
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
X_numerical = X[numerical_features]

print("Numerical features identified:", numerical_features)
print("Shape of numerical features before scaling:", X_numerical.shape)

# 5. Instantiate StandardScaler
scaler = StandardScaler()

# 6. Fit and transform the numerical features
X_scaled_array = scaler.fit_transform(X_numerical)

# 7. Convert the scaled numerical features back into a DataFrame
X_scaled = pd.DataFrame(X_scaled_array, columns=numerical_features, index=X.index)

print("Shape of scaled numerical features:", X_scaled.shape)
print("First 5 rows of scaled numerical features:")
print(X_scaled.head())

# 8. Concatenate the one-hot encoded categorical features and the scaled numerical features
X_processed = pd.concat([X_scaled, X_categorical], axis=1)

print("Shape of final preprocessed features (X_processed):", X_processed.shape)
print("First 5 rows of X_processed:")
print(X_processed.head())

"""**Reasoning**:
The previous code block correctly applied one-hot encoding and identified numerical features, but the 'Unnamed: 0' column, which was marked for dropping earlier, was inadvertently included in the numerical features for scaling. I need to explicitly drop 'Unnamed: 0' from the feature set `X` before identifying and scaling the numerical features to ensure proper preprocessing.


"""

import pandas as pd
from sklearn.preprocessing import StandardScaler

# 1. Separate features (X) from the target variable (y)
X = df.drop('label', axis=1)
y = df['label']

# Ensure 'Unnamed: 0' is dropped from X if it exists
if 'Unnamed: 0' in X.columns:
    X = X.drop('Unnamed: 0', axis=1)
    print("Dropped 'Unnamed: 0' column from features (X).")

print("Shape of X after dropping 'Unnamed: 0':", X.shape)
print("Shape of y:", y.shape)

# 2. Identify the categorical features
categorical_features = ['Industry', 'HostingProvider']

# 3. Apply one-hot encoding to these categorical features
X_categorical = pd.get_dummies(X[categorical_features], drop_first=True)

print("Shape of one-hot encoded categorical features:", X_categorical.shape)
print("First 5 rows of one-hot encoded categorical features:")
print(X_categorical.head())

# 4. Identify numerical features
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
X_numerical = X[numerical_features]

print("Numerical features identified:", numerical_features)
print("Shape of numerical features before scaling:", X_numerical.shape)

# 5. Instantiate StandardScaler
scaler = StandardScaler()

# 6. Fit and transform the numerical features
X_scaled_array = scaler.fit_transform(X_numerical)

# 7. Convert the scaled numerical features back into a DataFrame
X_scaled = pd.DataFrame(X_scaled_array, columns=numerical_features, index=X.index)

print("Shape of scaled numerical features:", X_scaled.shape)
print("First 5 rows of scaled numerical features:")
print(X_scaled.head())

# 8. Concatenate the one-hot encoded categorical features and the scaled numerical features
X_processed = pd.concat([X_scaled, X_categorical], axis=1)

print("Shape of final preprocessed features (X_processed):", X_processed.shape)
print("First 5 rows of X_processed:")
print(X_processed.head())

"""## Data Splitting

### Subtask:
Split the processed data into training and testing sets.

**Reasoning**:
To split the processed data into training and testing sets, I will import `train_test_split` and use it on `X_processed` and `y` with the specified parameters.
"""

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42, stratify=y)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""## Train Random Forest Classifier

### Subtask:
Initialize and train a Random Forest Classifier on the training data.

**Reasoning**:
To initialize and train a Random Forest Classifier, I will first import the necessary class, then instantiate it with a specified random state for reproducibility, and finally fit the model to the training data.
"""

from sklearn.ensemble import RandomForestClassifier

# Initialize the Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42)

# Train the classifier on the training data
rf_classifier.fit(X_train, y_train)

print("Random Forest Classifier trained successfully.")

"""## Evaluate Random Forest Classifier

### Subtask:
Evaluate the Random Forest Classifier's performance using relevant metrics (accuracy, precision, recall, F1-score, and ROC AUC).

**Reasoning**:
To evaluate the trained Random Forest Classifier, I will first make predictions on the test set (`X_test`), then calculate and print various performance metrics such as accuracy, precision, recall, F1-score, and ROC AUC.
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)
y_pred_proba = rf_classifier.predict_proba(X_test)[:, 1]

# Calculate performance metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_proba)

print(f"Model Performance Metrics:\n")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

"""## Final Task

### Subtask:
Summarize the performance of the classification model and discuss potential next steps for hyperparameter tuning, exploring other algorithms, or feature importance analysis.

## Summary:

### Q&A
The classification model (Random Forest Classifier) achieved an accuracy of 0.8271, precision of 0.8403, recall of 0.8469, F1-Score of 0.8436, and an ROC AUC of 0.8807 on the test set. The classification report and confusion matrix indicated balanced performance across classes.

Potential next steps for improvement include:
*   **Hyperparameter Tuning**: Optimize the Random Forest Classifier's hyperparameters (e.g., `n_estimators`, `max_depth`, `min_samples_split`, `min_samples_leaf`) using techniques like Grid Search or Random Search to enhance performance.
*   **Exploring Other Algorithms**: Investigate alternative classification algorithms such as Gradient Boosting Machines (e.g., XGBoost, LightGBM), Support Vector Machines (SVMs), or Neural Networks, which might capture different patterns in the data and yield better results.
*   **Feature Importance Analysis**: Conduct feature importance analysis using the trained Random Forest model or other methods to identify the most influential features. This could lead to feature engineering opportunities or feature selection to improve model efficiency and performance.

### Data Analysis Key Findings
*   Categorical features ('Industry', 'HostingProvider') were successfully one-hot encoded, resulting in 22 new features.
*   Numerical features were scaled using `StandardScaler`. An initial issue with an 'Unnamed: 0' column being included in numerical features was identified and corrected.
*   The final preprocessed feature set (`X_processed`) contains 34 features for 10,500 samples.
*   The data was split into training (8,400 samples) and testing (2,100 samples) sets with an 80/20 ratio, ensuring class proportion preservation using `stratify=y`.
*   A Random Forest Classifier was trained and evaluated, achieving the following performance on the test set:
    *   Accuracy: 0.8271
    *   Precision: 0.8403
    *   Recall: 0.8469
    *   F1-Score: 0.8436
    *   ROC AUC: 0.8807
*   The classification report and confusion matrix indicated balanced performance across the classes.

### Insights or Next Steps
*   The Random Forest Classifier provides a strong baseline performance, indicating the features are discriminative. Further optimization through hyperparameter tuning could lead to marginal gains.
*   Given the balanced performance metrics, exploring ensemble methods like Gradient Boosting could be beneficial, as they often outperform Random Forests, especially after careful tuning.

# Task
Train a Logistic Regression Classifier on the `X_train` and `y_train` datasets, ensuring to set `random_state=42` for reproducibility.

## Train Logistic Regression Classifier

### Subtask:
Initialize and train a Logistic Regression classifier on the preprocessed training data (`X_train`, `y_train`).

**Reasoning**:
To initialize and train a Logistic Regression classifier, I will import the `LogisticRegression` class, instantiate it with a specified `random_state` for reproducibility, and then fit the model to the training data (`X_train`, `y_train`).
"""

from sklearn.linear_model import LogisticRegression

# Initialize the Logistic Regression Classifier
logistic_reg_classifier = LogisticRegression(random_state=42, solver='liblinear') # Using 'liblinear' solver for better convergence with small datasets and L1/L2 regularization

# Train the classifier on the training data
logistic_reg_classifier.fit(X_train, y_train)

print("Logistic Regression Classifier trained successfully.")

"""## Evaluate Logistic Regression Performance

### Subtask:
Evaluate the Logistic Regression classifier's performance on the test set (`X_test`, `y_test`) using key classification metrics: accuracy, precision, recall, F1-score, and ROC AUC. We will also display the confusion matrix and classification report.

**Reasoning**:
To evaluate the trained Logistic Regression classifier, I will first make predictions and probability estimates on the test set, then calculate and print various performance metrics, including the classification report and confusion matrix.
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

# Make predictions on the test set
y_pred_lr = logistic_reg_classifier.predict(X_test)
y_pred_proba_lr = logistic_reg_classifier.predict_proba(X_test)[:, 1]

# Calculate performance metrics
accuracy_lr = accuracy_score(y_test, y_pred_lr)
precision_lr = precision_score(y_test, y_pred_lr)
recall_lr = recall_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)
roc_auc_lr = roc_auc_score(y_test, y_pred_proba_lr)

print(f"Logistic Regression Model Performance Metrics:\n")
print(f"Accuracy: {accuracy_lr:.4f}")
print(f"Precision: {precision_lr:.4f}")
print(f"Recall: {recall_lr:.4f}")
print(f"F1-Score: {f1_lr:.4f}")
print(f"ROC AUC: {roc_auc_lr:.4f}")

print("\nClassification Report (Logistic Regression):")
print(classification_report(y_test, y_pred_lr))

print("\nConfusion Matrix (Logistic Regression):")
print(confusion_matrix(y_test, y_pred_lr))

"""## Compare Model Performance

### Subtask:
Compare the performance metrics of the Logistic Regression model with those of the previously trained Random Forest Classifier to understand their relative strengths and weaknesses on this dataset.

**Reasoning**:
To compare the performance metrics of both models, I will create a pandas DataFrame to store the accuracy, precision, recall, F1-score, and ROC AUC for the Random Forest Classifier and the Logistic Regression Classifier, then display this comparison table.
"""

import pandas as pd

# Create a dictionary to store the performance metrics for both models
metrics_data = {
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC AUC'],
    'Random Forest': [accuracy, precision, recall, f1, roc_auc],
    'Logistic Regression': [accuracy_lr, precision_lr, recall_lr, f1_lr, roc_auc_lr]
}

# Create a DataFrame from the dictionary
performance_comparison_df = pd.DataFrame(metrics_data)

print("Model Performance Comparison:")
print(performance_comparison_df.round(4))

"""### Model Performance Summary

The Random Forest Classifier consistently outperformed the Logistic Regression model across all evaluated metrics. The Random Forest achieved a higher Accuracy (0.8271 vs 0.7790), Precision (0.8403 vs 0.7864), Recall (0.8469 vs 0.8218), F1-Score (0.8436 vs 0.8037), and a significantly better ROC AUC (0.8807 vs 0.8018). This indicates that the Random Forest Classifier is more effective in distinguishing between phishing and legitimate websites on this dataset, showcasing its strength in handling non-linear relationships and complex data patterns compared to the linear Logistic Regression model.

## Final Task

### Subtask:
Summarize the key findings from the Logistic Regression analysis, including its performance comparison with the Random Forest Classifier, and propose further steps for model selection or optimization.

## Summary:

### Q&A
The key findings from the Logistic Regression analysis indicate that it achieved an Accuracy of 0.7790, Precision of 0.7864, Recall of 0.8218, F1-Score of 0.8037, and ROC AUC of 0.8018.

When compared to the Random Forest Classifier, the Logistic Regression model performed worse across all metrics. The Random Forest Classifier achieved higher Accuracy (0.8271), Precision (0.8403), Recall (0.8469), F1-Score (0.8436), and a significantly higher ROC AUC (0.8807).

### Data Analysis Key Findings
*   The Logistic Regression model was successfully trained and evaluated, yielding the following performance metrics on the test set:
    *   Accuracy: 0.7790
    *   Precision: 0.7864
    *   Recall: 0.8218
    *   F1-Score: 0.8037
    *   ROC AUC: 0.8018
*   The confusion matrix for Logistic Regression indicated 686 True Negatives, 258 False Positives, 206 False Negatives, and 950 True Positives.
*   The Random Forest Classifier consistently outperformed the Logistic Regression model across all evaluated metrics, suggesting its superior ability to handle the dataset's complexities:
    *   Random Forest's Accuracy (0.8271) was higher than Logistic Regression's (0.7790).
    *   Random Forest's Precision (0.8403) was higher than Logistic Regression's (0.7864).
    *   Random Forest's Recall (0.8469) was higher than Logistic Regression's (0.8218).
    *   Random Forest's F1-Score (0.8436) was higher than Logistic Regression's (0.8037).
    *   Random Forest's ROC AUC (0.8807) was significantly higher than Logistic Regression's (0.8018).

### Insights or Next Steps
*   Given its superior performance, the Random Forest Classifier should be considered the primary candidate for further optimization and deployment for this phishing detection task.
*   Further model optimization could involve hyperparameter tuning for the Random Forest Classifier (e.g., using GridSearchCV or RandomizedSearchCV) or exploring ensemble methods that leverage the strengths of multiple models.
"""

print((performance_comparison_df))

"""# Task
Define a hyperparameter search space for a Random Forest Classifier including `n_estimators`, `max_features`, `max_depth`, `min_samples_split`, and `min_samples_leaf`. Then, use either `GridSearchCV` or `RandomizedSearchCV` from `sklearn.model_selection` with cross-validation on the training data (`X_train`, `y_train`), optimizing for a chosen scoring metric (e.g., F1-score or ROC AUC) to find the best hyperparameters. Finally, train a new Random Forest Classifier with these optimal hyperparameters, evaluate its performance on the test set (`X_test`, `y_test`) using accuracy, precision, recall, F1-score, ROC AUC, confusion matrix, and classification report, and summarize the results by comparing the tuned model's performance with the initial Random Forest model and discussing the impact of tuning.

## Define Hyperparameter Search Space

### Subtask:
Specify the range of values or options for key hyperparameters of the Random Forest Classifier (e.g., `n_estimators`, `max_features`, `max_depth`, `min_samples_split`, `min_samples_leaf`).

**Reasoning**:
To define the hyperparameter search space, I will create a dictionary named `param_grid` containing the specified ranges for `n_estimators`, `max_features`, `max_depth`, `min_samples_split`, and `min_samples_leaf` for the Random Forest Classifier.
"""

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_features': ['sqrt', 'log2', None],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

print("Defined hyperparameter search space (param_grid):")
print(param_grid)

"""**Reasoning**:
Now that the hyperparameter search space is defined, I will use `GridSearchCV` with 3-fold cross-validation on the training data (`X_train`, `y_train`) and optimize for the F1-score to find the best hyperparameters for the Random Forest Classifier.


"""

from sklearn.model_selection import GridSearchCV

# Initialize a Random Forest Classifier for GridSearchCV
rf = RandomForestClassifier(random_state=42)

# Initialize GridSearchCV with the defined parameter grid and a scoring metric (e.g., 'f1')
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid,
                           scoring='f1', cv=3, verbose=2, n_jobs=-1)

print("Starting GridSearchCV to find optimal hyperparameters...")

# Fit GridSearchCV to the training data
grid_search.fit(X_train, y_train)

print("GridSearchCV completed.")

# Get the best parameters and best score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

print(f"\nBest Hyperparameters found: {best_params}")
print(f"Best F1-score from cross-validation: {best_score:.4f}")

"""**Reasoning**:
Now that the optimal hyperparameters have been identified, I will train a new Random Forest Classifier using these `best_params` and then evaluate its performance on the test set.


"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

# Initialize the Random Forest Classifier with the best parameters found by GridSearchCV
rf_tuned_classifier = RandomForestClassifier(random_state=42, **best_params)

# Train the tuned classifier on the training data
rf_tuned_classifier.fit(X_train, y_train)

print("Tuned Random Forest Classifier trained successfully.")

# Make predictions on the test set using the tuned model
y_pred_tuned = rf_tuned_classifier.predict(X_test)
y_pred_proba_tuned = rf_tuned_classifier.predict_proba(X_test)[:, 1]

# Calculate performance metrics for the tuned model
accuracy_tuned = accuracy_score(y_test, y_pred_tuned)
precision_tuned = precision_score(y_test, y_pred_tuned)
recall_tuned = recall_score(y_test, y_pred_tuned)
f1_tuned = f1_score(y_test, y_pred_tuned)
roc_auc_tuned = roc_auc_score(y_test, y_pred_proba_tuned)

print(f"\nTuned Random Forest Model Performance Metrics:\n")
print(f"Accuracy: {accuracy_tuned:.4f}")
print(f"Precision: {precision_tuned:.4f}")
print(f"Recall: {recall_tuned:.4f}")
print(f"F1-Score: {f1_tuned:.4f}")
print(f"ROC AUC: {roc_auc_tuned:.4f}")

print("\nClassification Report (Tuned Random Forest):")
print(classification_report(y_test, y_pred_tuned))

print("\nConfusion Matrix (Tuned Random Forest):")
print(confusion_matrix(y_test, y_pred_tuned))

"""## Compare Tuned Random Forest with Logistic Regression

### Subtask:
Compare the performance metrics of the tuned Random Forest model with the Logistic Regression model.

**Reasoning**:
To compare the tuned Random Forest model with the Logistic Regression model, I will create a new pandas DataFrame to consolidate their performance metrics (Accuracy, Precision, Recall, F1-Score, and ROC AUC) and display it. This will provide a clear, direct comparison between the two algorithms after the Random Forest has been optimized.
"""

import pandas as pd

# Create a dictionary to store the performance metrics for both models
metrics_data_tuned_comparison = {
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC AUC'],
    'Tuned Random Forest': [accuracy_tuned, precision_tuned, recall_tuned, f1_tuned, roc_auc_tuned],
    'Logistic Regression': [accuracy_lr, precision_lr, recall_lr, f1_lr, roc_auc_lr]
}

# Create a DataFrame from the dictionary
performance_tuned_comparison_df = pd.DataFrame(metrics_data_tuned_comparison)

print("Model Performance Comparison (Tuned Random Forest vs. Logistic Regression):")
print((performance_tuned_comparison_df.round(4)))

"""## Summary of Tuned Random Forest Classifier Performance

The hyperparameter tuning process using `GridSearchCV` led to the selection of the following optimal parameters for the Random Forest Classifier:

*   `max_depth`: 10
*   `max_features`: 'sqrt'
*   `min_samples_leaf`: 1
*   `min_samples_split`: 2
*   `n_estimators`: 200

The performance metrics of the **Tuned Random Forest Classifier** on the test set are as follows:

*   **Accuracy**: 0.8405
*   **Precision**: 0.8812
*   **Recall**: 0.8209
*   **F1-Score**: 0.8500
*   **ROC AUC**: 0.8783

### Comparison with Initial Random Forest Classifier

Let's compare these results with the **Initial Random Forest Classifier** (before tuning):

| Metric    | Initial Random Forest | Tuned Random Forest |
| :-------- | :-------------------- | :------------------ |
| Accuracy  | 0.8271                | 0.8405              |
| Precision | 0.8403                | 0.8812              |
| Recall    | 0.8469                | 0.8209              |
| F1-Score  | 0.8436                | 0.8500              |
| ROC AUC   | 0.8807                | 0.8783              |

### Impact of Tuning

The hyperparameter tuning process resulted in a **modest improvement** in overall performance metrics for the Random Forest Classifier:

*   **Accuracy** increased from 0.8271 to 0.8405.
*   **Precision** saw a notable increase from 0.8403 to 0.8812, indicating that the tuned model makes fewer false positive predictions.
*   **F1-Score** also improved from 0.8436 to 0.8500, suggesting a better balance between precision and recall.
*   **Recall** slightly decreased from 0.8469 to 0.8209. While the model is slightly less effective at identifying all positive cases, the increase in precision might be a favorable trade-off depending on the specific application's cost of false positives versus false negatives.
*   **ROC AUC** remained very similar (0.8807 vs 0.8783), indicating that the model's ability to distinguish between classes is still strong and consistent.

Overall, tuning helped refine the model, leading to a slightly better performing classifier, especially in terms of precision, which is crucial in phishing detection to minimize legitimate websites being falsely flagged. The `max_depth=10` parameter suggests that a shallower tree structure was beneficial, preventing overfitting to some extent compared to deeper trees which might have been formed without this constraint.

## Final Task

### Subtask:
Summarize the results of the hyperparameter tuning, compare the performance of the tuned model with the initial Random Forest model, and discuss the impact of tuning.

## Summary:

### Q&A
1.  **What were the results of the hyperparameter tuning?**
    The optimal hyperparameters found for the Random Forest Classifier were: `max_depth=10`, `max_features='sqrt'`, `min_samples_leaf=1`, `min_samples_split=2`, and `n_estimators=200`. The best F1-score achieved during cross-validation with these parameters was 0.8651.

2.  **How does the performance of the tuned model compare with the initial Random Forest model?**
    The tuned Random Forest Classifier showed a modest improvement in performance compared to the initial model:
    *   **Accuracy:** Increased from 0.8271 to 0.8405.
    *   **Precision:** Notably increased from 0.8403 to 0.8812.
    *   **Recall:** Slightly decreased from 0.8469 to 0.8209.
    *   **F1-Score:** Improved from 0.8436 to 0.8500.
    *   **ROC AUC:** Remained very similar, going from 0.8807 to 0.8783.

3.  **What was the impact of tuning?**
    Tuning led to a slightly better performing classifier, especially in terms of precision, which is crucial for minimizing false positive predictions (e.g., flagging legitimate websites as phishing). The increase in F1-score indicates a better balance between precision and recall, despite a slight decrease in recall. The selection of `max_depth=10` suggests that a shallower tree structure was beneficial in preventing overfitting.

### Data Analysis Key Findings
*   The hyperparameter search space was defined for `n_estimators`, `max_features`, `max_depth`, `min_samples_split`, and `min_samples_leaf`.
*   `GridSearchCV` identified the optimal hyperparameters as `max_depth=10`, `max_features='sqrt'`, `min_samples_leaf=1`, `min_samples_split=2`, and `n_estimators=200`, achieving a cross-validation F1-score of 0.8651.
*   The tuned Random Forest model achieved the following performance on the test set: Accuracy: 0.8405, Precision: 0.8812, Recall: 0.8209, F1-Score: 0.8500, and ROC AUC: 0.8783.
*   Compared to the initial model, the tuned model showed an increase in Accuracy (0.8271 to 0.8405), Precision (0.8403 to 0.8812), and F1-Score (0.8436 to 0.8500), while Recall slightly decreased (0.8469 to 0.8209).

### Insights or Next Steps
*   The significant increase in precision for the tuned model suggests it is more effective at identifying positive cases correctly, which is valuable in scenarios where false positives are costly (e.g., mistakenly blocking a legitimate website).
*   While tuning yielded a modest overall improvement, exploring a wider range of hyperparameters or considering other optimization techniques like `RandomizedSearchCV` (which can be more efficient for larger search spaces) could potentially lead to further performance gains.
"""